### ISSUE TITLE
Home Assistant mqtt errors

### ISSUE THREAD

**Issue by TopdRob** [rvdbreemen/OTGW-firmware#225]
Logger: homeassistant.components.mqtt.models
Source: components/sensor/__init__.py:593
Integration: MQTT (documentation, issues)
First occurred: 15 september 2023 om 21:30:28 (82778 occurrences)
Last logged: 04:24:55

Exception raised when updating state of sensor.otgw_status_master, topic: 'OTGW/value/otgw-C8C9A35AC726/status_master' with payload: b'-----W--'
Exception raised when updating state of sensor.otgw_status_slave, topic: 'OTGW/value/otgw-C8C9A35AC726/status_slave' with payload: b'--------'
Exception raised when updating state of sensor.otgw_status_slave, topic: 'OTGW/value/otgw-C8C9A35AC726' with payload: b'online'
Exception raised when updating state of sensor.otgw_status_master, topic: 'OTGW/value/otgw-C8C9A35AC726' with payload: b'online'
Exception raised when updating state of sensor.otgw_status_slave, topic: 'OTGW/value/otgw-C8C9A35AC726/status_slave' with payload: b'--W-----'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 586, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '-----W--'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 589, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '-----W--'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 305, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 593, in state
    raise ValueError(
ValueError: Sensor sensor.otgw_status_master has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '-----W--' (<class 'str'>)

**Comment by rvdbreemen** [comment]
Known issue. Solved. Download mqttha.cfg from dev branch and upload it. 

And yes, I need to do a binary release.
